export const userConstants = {
    GET_REQUEST: 'USERS_GET_REQUEST',
    GET_SUCCESS: 'USERS_GET_SUCCESS',
    GET_FAILURE: 'USERS_GET_FAILURE',

    GET_REQUEST_LOAD_MORE: 'USERS_GET_REQUEST_LOAD_MORE',
    GET_SUCCESS_LOAD_MORE: 'USERS_GET_SUCCESS_LOAD_MORE',
    GET_FAILURE_LOAD_MORE: 'USERS_GET_FAILURE_LOAD_MORE',

    CHANGED_EXPANDED: 'CHANGED_EXPANDED'
}